config/routes.rb
# Presto::Config::Model.all.each { |model| puts model }
Presto::Engine.routes.draw do
  get '/', controller: :dashboard, action: :index, as: :dashboard
  scope 'models/:name/' do
    resources :items
  end
end

app/controllers/presto/application_controller.rb
module Presto
  class ApplicationController < ActionController::Base
  end
end

app/controllers/presto/dashboard_controller.rb
require_dependency "presto/application_controller"

module Presto
  class DashboardController < ApplicationController
    before_action :load_models

    def index
    end

    private
    def load_models
      @models_list = Presto::Config::Model.all
    end

    def load_class
      @klass = params[:name].classify.constantize
    end
  end
end

app/controllers/presto/items_controller.rb
require_dependency "presto/application_controller"
require_dependency "presto/load_relationships_attributes"

module Presto
  class ItemsController < ApplicationController
    before_action :load_class
    def index
      load_items
    end

    def show
      load_item
    end

    def new
      build_item
    end

    def create
      build_item
      save_item or render 'new'
    end

    def edit
      load_item
      build_item
    end

    def update
      load_item
      build_item
      save_item or render 'edit'
    end

    def destroy
      load_item
      @item.destroy
      redirect_to items_path(name: @klass)
    end

    private
    def load_items
      @q = item_scope.ransack(params[:q])
      @item_list = @q.result(distinct: true).paginate(page: params[:page])
    end

    def load_item
      @item ||= item_scope.find(params[:id])
    end

    def build_item
      @item ||= item_scope.build
      @item.attributes = item_params
      @klass.nested_attributes_options.keys.each do |nested_key|
        1.times { nested_relationship(nested_key).build } if Presto::nested_attributes && nested_relationship(nested_key).empty?
      end
    end

    def save_item
      redirect_to item_path(name: @klass.to_s.downcase, id: @item.id) if @item.save
    end

    def item_scope
      @klass.all
    end

    def item_params
      item_params = params[params[:name]]
      item_params ? item_params.permit(columns_names) : {}
    end

    def load_class
      @klass = params[:name].classify.constantize
    end

    def columns_names
      @klass_column_names ||= @klass.column_names.reject { |item| item == "id" }
      @klass_column_names.map { |column| column.to_sym } << Presto::LoadRelationshipsAttributes.new(model: @klass).klass_relationships
    end

    def nested_relationship(key)
      @item.send(key)
    end
  end
end

app/helpers/presto/application_helper.rb
module Presto
  module ApplicationHelper
    def model_list
      Presto::Config::Model.all
    end
  end
end

app/helpers/presto/items_helper.rb
module Presto
  module ItemsHelper
    def has_nested_relationship?
       Presto::nested_attributes
    end

    def search_text_field_sym(klass)
      (klass.column_types.to_a.map { |type| type[0] if string_or_text?(type)  }.compact.join("_or_") + "_cont").to_sym
    end
    def th_item(q,colum_name)
      return sort_link(q,colum_name) unless colum_name.include?("_id")
      sort_link(q,colum_name,colum_name.gsub("_id",""))
    end

    def td_item(model,name)
      return model.send(name.to_sym) unless name.include?("_id")
      val= model.send(name.to_sym)
      link_to val, edit_item_path(name.gsub("_id",""), val)
    end
    private
     def string_or_text?(column_type)
       val = column_type[1].class.to_s.split("::").last
       (val == "String" || val == "Text")
     end
  end
end

app/helpers/presto/welcome_helper.rb
module Presto
  module WelcomeHelper
  end
end

app/views/layouts/presto/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %title AdminLTE 2 | Starter
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", :rel => "stylesheet"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %link{:href => "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css", :rel => "stylesheet"}/
    = javascript_include_tag 'presto/application', 'data-turbolinks-track' => true
    = stylesheet_link_tag "presto/application", media: "all"
    / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
    / WARNING: Respond.js doesn't work if you view the page via file://
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  %body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      = render partial: "presto/header"
      = render partial: "presto/sidebar"
      .content-wrapper
        %section.content-header
          = yield :content_header
          %ol.breadcrumb
            %li
              %a{:href => "#"}
                %i.fa.fa-dashboard
                Level
            %li.active Here
        %section.content= yield
      = render partial: "presto/footer"
      = render partial: "presto/control_sidebar"

app/views/presto/_control_sidebar.html.haml
%aside.control-sidebar.control-sidebar-dark
  / Create the tabs
  %ul.nav.nav-tabs.nav-justified.control-sidebar-tabs
    %li.active
      %a{"data-toggle" => "tab", :href => "#control-sidebar-home-tab"}
        %i.fa.fa-home
    %li
      %a{"data-toggle" => "tab", :href => "#control-sidebar-settings-tab"}
        %i.fa.fa-gears
  / Tab panes
  .tab-content
    / Home tab content
    #control-sidebar-home-tab.tab-pane.active
      %h3.control-sidebar-heading Recent Activity
      %ul.control-sidebar-menu
        %li
          %a{:href => "javascript::;"}
            %i.menu-icon.fa.fa-birthday-cake.bg-red
            .menu-info
              %h4.control-sidebar-subheading Langdon's Birthday
              %p Will be 23 on April 24th
      / /.control-sidebar-menu
      %h3.control-sidebar-heading Tasks Progress
      %ul.control-sidebar-menu
        %li
          %a{:href => "javascript::;"}
            %h4.control-sidebar-subheading
              Custom Template Design
              %span.label.label-danger.pull-right 70%
            .progress.progress-xxs
              .progress-bar.progress-bar-danger{:style => "width: 70%"}
      / /.control-sidebar-menu
    / /.tab-pane
    / Stats tab content
    #control-sidebar-stats-tab.tab-pane Stats Tab Content
    / /.tab-pane
    / Settings tab content
    #control-sidebar-settings-tab.tab-pane
      %form{:method => "post"}
        %h3.control-sidebar-heading General Settings
        .form-group
          %label.control-sidebar-subheading
            Report panel usage
            %input.pull-right{:checked => "checked", :type => "checkbox"}/
          %p
            Some information about this general settings option
        / /.form-group
    / /.tab-pane
.control-sidebar-bg

app/views/presto/_footer.html.haml
%footer.main-footer
  / To the right
  .pull-right.hidden-xs
    Anything you want
  / Default to the left
  %strong
    Copyright © 2015
    = succeed "." do
      %a{:href => "#"} Company
  All rights reserved.

app/views/presto/_header.html.haml
%header.main-header
  / Logo
  = link_to dashboard_path, class: "logo" do
    / mini logo for sidebar mini 50x50 pixels
    %span.logo-mini
      %b> A
      LT
    / logo for regular state and mobile devices
    %span.logo-lg
      %b> Admin
      LTE
  / Header Navbar
  %nav.navbar.navbar-static-top{:role => "navigation"}
    / Sidebar toggle button
    %a.sidebar-toggle{"data-toggle" => "offcanvas", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
    / Navbar Right Menu
    .navbar-custom-menu
      %ul.nav.navbar-nav
        / Messages: style can be found in dropdown.less
        %li.dropdown.messages-menu
          / Menu toggle button
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-envelope-o
            %span.label.label-success 4
          %ul.dropdown-menu
            %li.header You have 4 messages
            %li
              / inner menu: contains the messages
              %ul.menu
                %li
                  / start message
                  %a{:href => "#"}
                    .pull-left
                      / User Image
                      = image_tag("presto/avatar-blank.jpg", class: "user-image")
                    / Message title and timestamp
                    %h4
                      Support Team
                      %small
                        %i.fa.fa-clock-o
                        5 mins
                    / The message
                    %p Why not buy a new awesome theme?
                / end message
              / /.menu
            %li.footer
              %a{:href => "#"} See All Messages
        / /.messages-menu
        / Notifications Menu
        %li.dropdown.notifications-menu
          / Menu toggle button
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-bell-o
            %span.label.label-warning 10
          %ul.dropdown-menu
            %li.header You have 10 notifications
            %li
              / Inner Menu: contains the notifications
              %ul.menu
                %li
                  / start notification
                  %a{:href => "#"}
                    %i.fa.fa-users.text-aqua
                    5 new members joined today
                / end notification
            %li.footer
              %a{:href => "#"} View all
        / Tasks Menu
        %li.dropdown.tasks-menu
          / Menu Toggle Button
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.fa.fa-flag-o
            %span.label.label-danger 9
          %ul.dropdown-menu
            %li.header You have 9 tasks
            %li
              / Inner menu: contains the tasks
              %ul.menu
                %li
                  / Task item
                  %a{:href => "#"}
                    / Task title and progress text
                    %h3
                      Design some buttons
                      %small.pull-right 20%
                    / The progress bar
                    .progress.xs
                      / Change the css width attribute to simulate progress
                      .progress-bar.progress-bar-aqua{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "20", :role => "progressbar", :style => "width: 20%"}
                        %span.sr-only 20% Complete
                / end task item
            %li.footer
              %a{:href => "#"} View all tasks
        / User Account Menu
        %li.dropdown.user.user-menu
          / Menu Toggle Button
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            / The user image in the navbar
            = image_tag("presto/avatar-blank.jpg", class: "user-image")
            / hidden-xs hides the username on small devices so only the image appears.
            %span.hidden-xs Alexander Pierce
          %ul.dropdown-menu
            / The user image in the menu
            %li.user-header
              = image_tag("presto/avatar-blank.jpg", class: "user-image")
              %p
                Alexander Pierce - Web Developer
                %small Member since Nov. 2012
            / Menu Body
            %li.user-body
              .col-xs-4.text-center
                %a{:href => "#"} Followers
              .col-xs-4.text-center
                %a{:href => "#"} Sales
              .col-xs-4.text-center
                %a{:href => "#"} Friends
            / Menu Footer
            %li.user-footer
              .pull-left
                %a.btn.btn-default.btn-flat{:href => "#"} Profile
              .pull-right
                %a.btn.btn-default.btn-flat{:href => "#"} Sign out
        / Control Sidebar Toggle Button
        %li
          %a{"data-toggle" => "control-sidebar", :href => "#"}
            %i.fa.fa-gears

app/views/presto/_sidebar.html.haml
%aside.main-sidebar
  / sidebar: style can be found in sidebar.less
  %section.sidebar
    / Sidebar user panel (optional)
    .user-panel
      .pull-left.image
        %img.img-circle{:alt => "User Image", :src => "http://img2.wikia.nocookie.net/__cb20130607025329/creepypasta/images/3/38/Avatar-blank.jpg"}/
      .pull-left.info
        %p Alexander Pierce
        / Status
        %a{:href => "#"}
          %i.fa.fa-circle.text-success
          Online
    / search form (Optional)
    %form.sidebar-form{:action => "#", :method => "get"}
      .input-group
        %input.form-control{:name => "q", :placeholder => "Search...", :type => "text"}/
        %span.input-group-btn
          %button#search-btn.btn.btn-flat{:name => "search", :type => "submit"}
            %i.fa.fa-search
    / /.search form
    / Sidebar Menu
    %ul.sidebar-menu= render partial: "presto/dashboard/menu_li", collection: model_list, as: :model

app/views/presto/dashboard/_menu_li.html.haml
%li{class: "#{'active' if params[:name] == model.singularize }"}
  = link_to items_path(name: model.singularize) do
    %i.fa.fa-link
    %span= model.singularize

app/views/presto/dashboard/index.html.haml
/ Small boxes (Stat box)
- content_for :content_header do
  %h1
    Dashboard
    %small Control panel
%p Modes in de app
%p= Presto::demo
%ul= render partial: "menu_li", collection: @models_list, as: :model

app/views/presto/items/_form.html.haml
%p
  Adding new #{klass.to_s.downcase}
%div
  = semantic_form_for item, url: url do |f|
    = f.inputs
    = render partial: "presto/items/nested_forms", locals: {f: f}
    = f.actions

app/views/presto/items/_item.html.haml
%tr
  - klass.column_names.each do |name|
    %td= td_item(model,name)
  %td
    = link_to item_path(klass, model), method: :delete, data: { confirm: "Are you sure ?" } do
      %span.glyphicon.glyphicon-trash{"aria-hidden" => "true"}
  %td
    = link_to edit_item_path(klass.to_s.downcase, model) do
      %span.glyphicon.glyphicon-edit{"aria-hidden" => "true"}

app/views/presto/items/_nested_forms.html.haml
- if has_nested_relationship?
  - @klass.nested_attributes_options.keys.each do |nested_key|
    %fieldset
      %legend= nested_key.to_s.upcase
    = f.semantic_fields_for nested_key do |nested|
      - fields = nested_key.to_s.classify.constantize.column_names - ["created_at", "updated_at", "id", "#{@klass.to_s.downcase}_id"]
      - fields.each do |column|
        - if column.to_s.include?('_id')
          = nested.input column.to_s.gsub('_id','').to_sym
        - else
          = nested.input column

app/views/presto/items/edit.html.haml
= render "form", klass: @klass, item: @item, url: presto.item_path(@klass.to_s.downcase, @item)

app/views/presto/items/index.html.haml
- content_for :content_header do
  %h1
    = @klass.to_s.capitalize
    %small Control panel
.box
  / Default box contents
  .box-header.with-border
    = @klass.to_s
    list
  .box-body
    .row
      .col-lg-5
        = search_form_for @q, url: items_path(@klass.to_s.downcase), class: 'form-inline' do |f|
          = f.label :search
          = f.search_field search_text_field_sym(@klass), class: 'form-control'
      .col-lg-3
        - if params[:q]
          = link_to "Clear", items_path(@klass.to_s.downcase)
      .col-lg-3
        = link_to "create new", new_item_path, class: "btn btn-primary"
    %hr
    %table.table.dataTable
      %thead
        %tr
          - @klass.column_names.each do |name|
            %th= th_item(@q,name)
          %th
      %tbody= render partial: "item", collection: @item_list, as: :model, locals: {klass: @klass}
    = will_paginate @item_list, renderer: ::BootstrapPagination::Rails

app/views/presto/items/new.html.haml
= render "form", klass: @klass, item: @item, url: items_path(@klass.to_s.downcase)

app/views/presto/items/show.html.haml
%h1= @klass.to_s
.row
  = link_to "Return to #{@klass} list ", items_path(name: @klass.to_s.downcase), class: "btn btn-primary"
%p Fields
%ul
  - @item.attributes.each do |column|
    %li= "#{column[0]} == #{column[1]}"

app/views/presto/welcome/demo.erb
<h1>
  demo.erb
</h1>

app/views/presto/welcome/index.html.haml
%h1
  Hola mundo index Presto::Index
models
%ul
  - @models.each do |model|
    %li
      = model.to_s
gems
%ul
  - @gems.each do |gem|
    %li
      = gem.to_s